[package]
name = "chron_tui"
description = "Configure your Keychron mouse from the terminal"
license = "LGPL-3.0-or-later"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.28"
hidapi = "2.6"
ratatui = "0.29.0"
color-eyre = "0.6.5"
